### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by joaogbcravo** [twilson63/s3fs-recipe#22]
In metadata.rb and README.md files it is listed as mandatory attributes ["s3fs"]["data_bag"]["name"] and  ["s3fs"]["data_bag"]["name"]  to load data bag itens. However data bags are not used by the cookbook. 

The documentation should be updated to remove the references to data bags and use add references to the mandatory node['s3fs']['data'] attribute instead.

**Comment by DarkGigaByte** [comment]
+1, i just fucking debugged why it does not work like described... suspected the error in front of the display. :( 

But i prefer to update the code instead of the documentation. It would be nice to point to a data bag.

**Comment by DarkGigaByte** [comment]
Maybe close this issue now?! ;)
